# Generated by Django 5.1.15 on 2026-04-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('file', models.FileField(upload_to='logs/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Завантажено')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Очікує обробки'), ('processing', 'Обробляється'), ('done', 'Оброблено'), ('error', 'Помилка')], default='pending', max_length=20)),
                ('total_lines', models.PositiveIntegerField(default=0)),
                ('parsed_lines', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Лог-файл',
                'verbose_name_plural': 'Лог-файли',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('upload_done', 'Файл оброблено'), ('anomaly', 'Виявлено аномалію'), ('upload_failed', 'Помилка обробки')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.logfile')),
            ],
            options={
                'verbose_name': 'Сповіщення',
                'verbose_name_plural': 'Сповіщення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analytics.logfile')),
            ],
            options={
                'verbose_name': 'Звіт',
                'verbose_name_plural': 'Звіти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('group', 'Група секцій'), ('chart', 'Графік'), ('table', 'Таблиця'), ('metric', 'Метрика')], max_length=20)),
                ('chart_kind', models.CharField(blank=True, choices=[('line', 'Лінійний'), ('bar', 'Стовпчастий'), ('pie', 'Кругова'), ('doughnut', 'Кільцева')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='analytics.reportsection')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='analytics.report')),
            ],
            options={
                'verbose_name': 'Секція звіту',
                'verbose_name_plural': 'Секції звіту',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=2048)),
                ('status_code', models.PositiveSmallIntegerField(db_index=True)),
                ('response_size', models.PositiveIntegerField(default=0)),
                ('referer', models.CharField(blank=True, max_length=2048)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, db_index=True, max_length=100)),
                ('os_family', models.CharField(blank=True, db_index=True, max_length=100)),
                ('device_type', models.CharField(blank=True, db_index=True, max_length=20)),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='analytics.logfile')),
            ],
            options={
                'verbose_name': 'Запис логу',
                'verbose_name_plural': 'Записи логу',
                'indexes': [models.Index(fields=['status_code', 'timestamp'], name='analytics_l_status__dc1136_idx'), models.Index(fields=['log_file', 'timestamp'], name='analytics_l_log_fil_633282_idx')],
            },
        ),
    ]
